version : '3.8'


services:
  db:
    container_name: postgres_demo
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=dice_db
    ports:
     - "5432:5432"
    volumes:
     - ./data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: duclos.alex85@outlook.fr
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
