BEGIN;

DROP TABLE IF EXISTS "Users_and_Games",
"Games",
"Users";

CREATE TABLE IF NOT EXISTS "Users" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "pseudo" TEXT NOT NULL UNIQUE,
    "password" TEXT NOT NULL,
    "email" TEXT NOT NULL UNIQUE,
    "is_admin" BOOLEAN NOT NULL DEFAULT FALSE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, -- on peut également utiliser NOW()
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "Games" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL UNIQUE,
    "description" TEXT NOT NULL,
    "max_players" INT NOT NULL,
    "notes" TEXT,
    "user_id" INT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'en cours',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, -- on peut également utiliser NOW()
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "Users_and_Games" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" INT NOT NULL REFERENCES "Users"("id"),
    "game_id" INT NOT NULL REFERENCES "Games"("id")
);

COMMIT;