BEGIN;

DROP TABLE IF EXISTS "users_and_games",
"Games",
"Users";

CREATE TABLE IF NOT EXISTS "users" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "pseudo" TEXT NOT NULL UNIQUE,
    "password" TEXT NOT NULL,
    "email" TEXT NOT NULL UNIQUE,
    "is_admin" BOOLEAN NOT NULL DEFAULT FALSE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, -- on peut également utiliser NOW()
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "games" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL UNIQUE,
    "description" TEXT NOT NULL,
    "max_players" INT NOT NULL,
    "notes" TEXT,
    "user_id" INT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'en cours',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, -- on peut également utiliser NOW()
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "users_and_games" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" INT NOT NULL REFERENCES "users"("id"),
    "game_id" INT NOT NULL REFERENCES "games"("id")
);

COMMIT;